### ISSUE TITLE
pyprops.hxx: No such fie or directory

### ISSUE THREAD

**Issue by mglass21** [RiceCreekUAS/rc-flight#4]
not finding this file in /src/actuators/act_fgfs.cxx
causing fatal error in build
fatal error: pyprops.hxx: No such file or directory
 #include <pyprops.hxx>
thanks

**Comment by clolsonus** [comment]
Sorry, I made an organizational change and didn't communicate that very well.  The aura-props package (a repository here under AuraUAS) now installs in two parts.

1. cd to aura-props/library and run: ./autogen.sh  then run the commands that suggests at the end to create a build dir, configure, and install.

2. cd back over to aura-props/python and run: sudo python3 ./setup.py install

I'm happy to help if you run into further issues.

**Comment by clolsonus** [comment]
Quick follow up, I have refactored the property tree system and reengineered it on top of the rapidjson library for dynamic tree building and memory management (also loading/saving the property tree as a json format file and pretty printing.)  The rc-flight code has been updated for the new property tree api.
